# -*- org-adapt-indentation: nil; org-edit-src-content-indentation: 0; org-src-preserve-indentation: t; -*-
#+TITLE: Emacs Init File
#+PROPERTY: tangle no
#+PROPERTY: noweb yes
#+PROPERTY: noweb-ref runtime-configuration
#+PROPERTY: results silent

* Install

This config is bootstrapped by evaluating the source block below (<kbd>C-c C-c</kbd>).

The file must be saved in `user-emacs-directory` (=~/.emacs.d= by default).

Make sure the properties at the top of the file are initialized before evaluating the block.

#+BEGIN_SRC emacs-lisp :tangle yes :noweb-ref none
;; This is the only source block in the file that gets tangled. All
;; other source blocks will be embedded in the codition below using
;; noweb references.
;; 
;; Special properties at the top of this file assigns default
;; reference name to every block and excludes them from tangling. This
;; block overrides this configuraiton using header props.
;;
;; The condition below evaluates the content of all other blocks when
;; init.el is newer than init.el, otherwise it reinitializes init.el
;; from init.org and evaulates it after init.el gets updated.
(if (file-newer-than-file-p (expand-file-name "init.org" user-emacs-directory)
			    (expand-file-name "init.el" user-emacs-directory))
    (org-babel-load-file (expand-file-name "init.org" user-emacs-directory) t)
  <<runtime-configuration>>)
#+END_SRC

** Package Manager

Some of the configuration relies on third-party packages which are pulled separately.

I like to center my configuration around concepts and not tools, which is why I prefer prefer [el-get](https://github.com/dimitri/el-get) over [use-package](https://github.com/jwiegley/use-package).

*** Package.el

Package.el is used as one of el-get's installation methods and it is also used to install el-get.

#+BEGIN_SRC emacs-lisp
(require 'package)
(add-to-list 'package-archives
	     '("melpa" . "https://melpa.org/packages/"))
(package-initialize)
#+END_SRC

*** El-get

This script makes sure that el-get is installed and available.

#+BEGIN_SRC emacs-lisp
(add-to-list 'load-path (expand-file-name "el-get/el-get" user-emacs-directory))

(unless (require 'el-get nil 'noerror)
  (package-refresh-contents)
  (package-install 'el-get)
  (require 'el-get)
  ;; Use el-get to reinstall el-get to pull all the recipes
  (el-get 'sync "el-get"))
#+END_SRC

* General

Basic configuration applicable to every activity.

** Better defaults

Below are some of the sane defaults that make my life easier.

#+BEGIN_SRC emacs-lisp
;; Remap <C-h> to <DEL> for accessiblity
(keyboard-translate ?\C-h ?\C-?)

;; Answer confirmation dialogs with a single key
(defalias 'yes-or-no-p 'y-or-n-p)

;; Better naming style for conflicting buffers
(setq uniquify-buffer-name-style 'reverse)

;; Enable persistent minibuffer history
(savehist-mode 1)

;; Save clipboard contents to kill ring instead of discarding them
(setq save-interprogram-paste-before-kill t)

;; Move backups and auto-save files to home directory to avoid cluttering work dir
(setq backup-directory-alist
      `((".*" . ,(expand-file-name "backups" user-emacs-directory))))
(setq auto-save-file-name-transforms
      `((".*" ,(expand-file-name "backups" user-emacs-directory) t)))
(setq auto-save-list-file-prefix 
      (expand-file-name "backups/" user-emacs-directory))

;; Disable ring bell on `keyboard-quit` (<C-g>)
(setq ring-bell-function 'ignore)
#+END_SRC

** Display

Change default emacs appearance

#+BEGIN_SRC emacs-lisp
(tool-bar-mode -1)
(scroll-bar-mode -1)

;; Hide menu-bar unless on Mac OS X where it doesn't take away any real estate
(unless (eq window-system 'mac)
  (menu-bar-mode -1))

(set-frame-font "DejaVu Sans Mono-12" 'keep-size t)

;; Leuven is a light theme with supporting many modes
(load-theme 'leuven 'no-confirm)

;; Start emacs in fullscreen
(setq initial-frame-alist '((fullscreen . maximized)))
#+end_src


* Version Control

Configuration for Version Control tools.

** Magit

Magit is a Git interface for emacs. It helps tremendously with partial commits, rebase and history browsing.

#+BEGIN_SRC emacs-lisp
(el-get 'sync "magit")

(global-set-key (kbd "C-x g g") 'magit-status)
#+END_SRC

** Git Timemachine

Git timemachine allows you to quickly review the history of a signle file

#+BEGIN_SRC emacs-lisp
(el-get 'sync "git-timemachine")

(global-set-key (kbd "C-x g t") 'git-timemachine)
#+END_SRC

** Git Gutter

#+BEGIN_SRC emacs-lisp
(el-get 'sync "git-gutter")

(global-git-gutter-mode 1)
#+END_SRC

** Ediff

Ediff starts in the new frame by defualt. This change makes ediff reuse existing frame and restore window layout on exit.

#+BEGIN_SRC emacs-lisp
(setq ediff-window-setup-function 'ediff-setup-windows-plain)
#+END_SRC
* Multiple Cursors

